#!/usr/bin/env ruby
# encoding: utf-8

############################################################################
#                         					           #
#  quick script for extracting texts from gutenberg books (output: json)   #
#								           #
#  scripts/gutenberg resources/[language]/gutenberg resources/[language]/  #
#									   #
############################################################################

begin

	require 'nokogiri'

	require 'oj'

rescue LoadError

	puts ':('

	exit()

end

files, books, total_paragraphs, total_words = Dir[ File.join( ARGV[0], '*.txt' ) ], {}, 0, 0

files.each do |book|

	book_name = File.basename( book )

	books.store( book_name, [] )

	File.read( book ).split("\n").each do |paragraph|

		books[book_name] << paragraph

		total_paragraphs += 1

		total_words += paragraph.split.size

	end

end

open( File.join(ARGV[1], 'gutenberg.json'), 'w') do |f|

	f.print( Oj.dump( books ) )

end

puts "--- total books: #{books.size}, paragraphs: #{total_paragraphs}, words: #{total_words}"
