#!/usr/bin/env ruby
# encoding: utf-8

require './language'
include Language

['spanish', 'french', 'italian', 'english', 'portuguese'].each do |input_language|

#	NGram::ngrams_please( File.join( 'resources', input_language, 'gutenberg.json' ), :abc, File.join( 'tmp', input_language ) )

	NGram::ngrams_please( File.join( 'resources', input_language, 'gutenberg.json' ), 3, File.join( 'tmp', input_language ) )

end
